[package]
name = "colorcycle"
version = "0.1.0"
authors = ["aquova <abrick912@gmail.com>"]
edition = "2018"

[dependencies]
argparse = "0.2.2"
chrono = "0.4"
sdl2 = "^0.34.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
